# Generated by Django 5.0.6 on 2024-05-21 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productprice_url_alter_productprice_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productprice',
            name='website',
        ),
        migrations.AddField(
            model_name='productprice',
            name='source',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productprice',
            name='price',
            field=models.FloatField(),
        ),
    ]
